### ISSUE TITLE
Implement basic 3D model interactions using UI controls

### ISSUE THREAD

**Issue by meghnaravikumar** [HarshitSohaney/ECE496#12]
## Description 
Add UI controls for basic interactions with the 3D models on the viewer panel, including the ability to (1) rotate, (2) scale, and (3) translate.

## Subtasks 

- [ ] Add controls for rotating the 3D model.
- [ ] Add controls for scaling the 3D model.
- [ ] Add controls for translating the 3D model.

## Acceptance Criteria 

- Users can rotate a 3D model in the viewer panel.
- Users can scale a 3D model in the viewer panel.
- Users can translate a 3D model in the viewer panel.

## Attachments

_[Links to relevant documents, designs, or resources]_

## Dependencies

- [x] #11 
- [x] #10
