### ISSUE TITLE
Color Change Animation

### ISSUE THREAD

**Issue by annechoww** [HarshitSohaney/ECE496#127]
## Description 
Allow the color of an asset to be animated if desired. I.e. the user must be able to apply a color change and have that change be saved in the animation sequence. 

## Subtasks 

- [ ] Animate in Canvas
- [ ] Ensure colour change works in preview
- [ ] Ensure colour change works in publish 

## Acceptance Criteria 

- Colour change animation should opperate as any other operation in all environments.

## Attachments
