### ISSUE TITLE
Connect canvas to AR environment

### ISSUE THREAD

**Issue by annechoww** [HarshitSohaney/ECE496#18]
## Description 
Connect the canvas (content builder) to the A-Frame AR Porjection to be able to project assets selected via drag and drop.

## Subtasks 

- [x] Integrate A-frame to in react
- [x] Modify scenebuilder to return/export the scene created in canvas
- [x] Convert exported scene to AR with A-frame

## Acceptance Criteria 

- Can project assets dropped into canvas in AR space

## Attachments

_https://www.npmjs.com/package/aframe-react_
