### ISSUE TITLE
Creating Assets with Unity

### ISSUE THREAD

**Issue by annechoww** [HarshitSohaney/ECE496#5]
## Description 
Research and document how to use Unity to create a 3D asset. Output few usable assets for prototype.

## Subtasks 

- [x] Research and document the process of creating a 3D asset with Unity
- [x] Experiment and document the usage of shaders, materials and meshes to vary the 3D asset appearance. 
- [x] Play around with the motions/transforms and physics of the object. Document the process

## Acceptance Criteria 

- Detailed and well-researched documents that outline the asset creation and the basic transforms (rotate, translation, etc.) of an object
- Creation of basic, simple assets usable for prototype

## Attachments

_[Links to relevant documents, designs, or resources]_
