### ISSUE TITLE
Animation sequencing for single object’s position

### ISSUE THREAD

**Issue by meghnaravikumar** [HarshitSohaney/ECE496#80]
## Description 
We have the basic UI for the animation editor. Now, we need to implement the ability to sequence one object's position. 

IMPORTANT: make sure that when the keyframe bars are adjusted (resized or moved), the animation sequence actually adapts to that. Additionally, consider what will occur when the keyframe bar doesn't start at 0s.

## Subtasks 

- [ ] Keep track of the object's position when the "add keyframe" button (the diamond button on the timeline toolbar shown below) is pressed 
<img width="230" alt="image" src="https://github.com/user-attachments/assets/48c41347-572d-4abe-af92-77717336f844">

- [ ] Add a keyframe bar with a start and end position
- [ ] When play is pressed the object's animation sequence moves

## Acceptance Criteria 

- Criteria 1
- Criteria 2
- Criteria 3

## Attachments

_[Links to relevant documents, designs, or resources]_

## Dependencies

- [ ] #77
