### ISSUE TITLE
Add rotation and scale properties in animation sequencing

### ISSUE THREAD

**Issue by meghnaravikumar** [HarshitSohaney/ECE496#90]
## Description

Currently, the keyframe structure in the `AnimationController` handles position animation as follows:

```javascript
{
  id: 1,
  start: 0,
  end: 5,
  position: {
    start: [x1, y1, z1],
    end: [x2, y2, z2],
  },
  // ... other properties
}
```

We need to extend this structure to include rotation and scale, resulting in the following format:

```javascript
{
  id: 1,
  start: 0,
  end: 5,
  position: {
    start: [x1, y1, z1],
    end: [x2, y2, z2],
  },
  rotation: {
    start: [rx1, ry1, rz1],
    end: [rx2, ry2, rz2],
  },
  scale: {
    start: [sx1, sy1, sz1],
    end: [sx2, sy2, sz2],
  },
}
```

### Rotation Interpolation

Interpolating rotation is complex due to potential gimbal lock issues when using Euler angles. We have two options:

- **Euler Angles**: Linear interpolation (LERP) can be used but may cause gimbal lock. Suitable for simple cases.
- **Quaternions**: Use spherical linear interpolation (SLERP) for smooth rotation without gimbal lock. This requires more advanced mathematics or utilizing a library like Three.js's `Quaternion.slerp`.

## Subtasks

- [ ] **Modify `addKeyframe` in `AnimationController` to capture rotation and scale:**
  - Update the function to include the object's current rotation and scale when creating or ending a keyframe.
- [ ] **Modify `interpolateProperties` to interpolate rotation and scale:**
  - Extend the interpolation logic to handle rotation and scale alongside position.
  - Consider using quaternions and SLERP for rotation interpolation to avoid gimbal lock.
- [ ] **In `ARObject.js`, apply the interpolated rotation and scale to the mesh:**
  - Update the mesh's rotation and scale properties based on the interpolated values during the render loop.

## Acceptance Criteria

- The keyframe data structure includes `rotation` and `scale` properties, mirroring the structure used for `position`.
- When keyframes are created or updated, the object's rotation and scale are correctly captured.
- The `interpolateProperties` function successfully interpolates position, rotation, and scale over time.
- Rotation interpolation is smooth and free from gimbal lock issues, ideally using quaternions and SLERP.
- The `ARObject` component accurately applies interpolated position, rotation, and scale to the mesh each frame.
- Existing position animations continue to function correctly without regression.

## Attachments

- [Three.js Quaternion Documentation](https://threejs.org/docs/#api/en/math/Quaternion)
- [Three.js Euler Documentation](https://threejs.org/docs/#api/en/math/Euler)
- [Understanding Quaternions and SLERP](https://en.wikipedia.org/wiki/Slerp)

## Dependencies

- [x] #80 
- [x] #82
